apiVersion: v1
kind: Service
metadata:
  name: faas-svc
spec:
  selector:
    role: app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32001
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: faas-deployment
  labels:
    role: app
spec:
  replicas: 1
  selector:
    matchLabels:
      role: app
  template:
    metadata:
      labels:
        role: app
    spec:
      containers:
      - name: app
        image: "magalixcorp/faasapp"
      - name: web
        image: "magalixcorp/faasweb"